name 'formatron_erlang'
version '0.1.1'
description 'Formatron Erlang cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/erlang-cookbook'
issues_url 'https://github.com/formatron/erlang-cookbook/issues'
supports 'ubuntu'
depends 'apt'
